{
 "title": "Konduktor",
 "description": "This dashboard is to display running jobs and DCGM metrics from a Kubernetes cluster.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   { "name": "gpu", "query": "label_values(gpu)" },
   {
    "name": "workloads",
    "query": {
     "query": "label_values(kube_pod_labels,label_kueue_x_k8s_io_pod_group_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPUs allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(modelName) (label_replace(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\", namespace!='kube-system'}, \"kubernetes_node\", \"$1\", \"node\", \"(.+)\") + on(kubernetes_node) group_left() DCGM_FI_DEV_DEC_UTIL{gpu=\"0\"} * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_pending_workloads{status=\"inadmissible\"}) by (cluster_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (label_kueue_x_k8s_io_pod_group_name, namespace) ((sum_over_time(kube_pod_status_phase{phase=\"Pending\"}[7d]) * kube_pod_status_phase{phase=\"Pending\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n) > 0) * 30",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_kueue_x_k8s_io_pod_group_name, namespace) ((\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} \n  * on(namespace, pod) group_left()\n    kube_pod_status_phase{phase=\"Pending\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GPUs (Instant)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{job=\"gpu-metrics\"}) by (modelName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster GPU Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_COPY_UTIL{job=\"gpu-metrics\"}) / (count(DCGM_FI_DEV_MEM_COPY_UTIL{job=\"gpu-metrics\"}) * 100) * 100"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_admitted_active_workloads) by (cluster_queue) + 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active workloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (label_kueue_x_k8s_io_pod_group_name, namespace) ((sum_over_time(kube_pod_status_phase{phase=\"Running\"}[7d]) * kube_pod_status_phase{phase=\"Running\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n) > 0) * 30",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_kueue_x_k8s_io_pod_group_name, namespace) ((\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} \n  * on(namespace, pod) group_left()\n    kube_pod_status_phase{phase=\"Running\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DCGM Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}