{
 "title": "Konduktor - user (NEBIUS)",
 "description": "This dashboard is to display running jobs and DCGM metrics from a Kubernetes cluster.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "workloads",
    "query": {
     "query": "query_result(last_over_time(kube_pod_labels{namespace='default'}[$__range]))"
    }
   },
   { "name": "gpu", "query": { "query": "label_values(gpu)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"default\", label_kueue_x_k8s_io_pod_group_name=~\"$workloads\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU Stats Done", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{gpu=~\"${gpu}\", pod=~\"${pod}\"} * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "GPU SM Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE{gpu=~\"${gpu}\", pod=~\"${pod}\"} * 100 * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=~\"${gpu}\", pod=~\"${pod}\"} * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=~\"${gpu}\", pod=~\"${pod}\"} * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{gpu=~\"${gpu}\", pod=~\"${pod}\"} * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "NVLINK Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{gpu=~\"${gpu}\", pod=~\"${pod}\"} * 1e6 * on (pod) group_left(kube_pod_labels) kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}"
    }
   ]
  },
  {
   "title": "Infiniband Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=\"default\", pod=~\"${pod}\", label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"} * on(pod) group_left(node, host_ip) kube_pod_info * on(host_ip) group_left(instance) label_replace(sum by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total[1m])), \"host_ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{pod}} ON {{node}}"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Utilization (By Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_pod, node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace='default', pod=~\"${pod}\"} * on(pod) group_left(exported_pod) label_replace(kube_pod_labels{namespace='default', pod=~\"${pod}\", label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}, \"exported_pod\", \"$1\", \"pod\", \"(.+)\")) * 100 / on(node) group_left kube_node_status_capacity{resource='cpu'}",
     "legendFormat": "{{exported_pod}} ON {{node}}"
    }
   ]
  },
  {
   "title": "CPU Memory (By Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_pod, node) (container_memory_working_set_bytes{namespace='default', pod=~\"${pod}\"} * on(pod) group_left(exported_pod) label_replace(kube_pod_labels{namespace='default', pod=~\"${pod}\", label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}, \"exported_pod\", \"$1\", \"pod\", \"(.+)\")) * 100 / on(node) group_left kube_node_status_capacity{resource='memory'}",
     "legendFormat": "{{exported_pod}} ON {{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage (Whole Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=\"default\", pod=~\"${pod}\", label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"} * on(pod) group_left(node, host_ip) kube_pod_info * on(host_ip) group_left(instance) label_replace(100 * (1 - (max by (instance) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}) / max by (instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}))), \"host_ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{pod}} ON {{node}}"
    }
   ]
  },
  {
   "title": "Node RAM Usage (Whole Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace='default', pod=~\"${pod}\", label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"} * on(pod) group_left(node, host_ip) kube_pod_info * on(host_ip) group_left(instance) label_replace(100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes), \"host_ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{pod}} ON {{node}}"
    }
   ]
  },
  {
   "title": "Active workloads (Kueue)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (label_kueue_x_k8s_io_pod_group_name, namespace) ((sum_over_time(kube_pod_status_phase{phase=\"Running\"}[7d]) * kube_pod_status_phase{phase=\"Running\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n) > 0) * 30",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_kueue_x_k8s_io_pod_group_name, namespace) ((\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} \n  * on(namespace, pod) group_left()\n    kube_pod_status_phase{phase=\"Running\"}\n  + on(namespace, pod) group_left(label_kueue_x_k8s_io_pod_group_name)\n    kube_pod_labels{label_kueue_x_k8s_io_pod_group_name=~\"(.+)\"} * 0\n)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod logs",
   "type": "logs",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"default\", k8s_pod_name=~\"${pod}\"} | logfmt"
    }
   ]
  },
  {
   "title": "Total GPUs (Instant)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{gpu=~\"${gpu}\", pod=~\"${pod}\"} * on (pod) group_left(kube_pod_labels) label_replace(kube_pod_labels{namespace='default', label_kueue_x_k8s_io_pod_group_name=~\"${workloads}\"}, \"exported_pod\", \"$1\", \"pod\", \"(.+)\") ) by (modelName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network received bytes total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (device) (\n    rate(node_network_receive_bytes_total{job=\"node-exporter\", device!=\"lo\"}[5m])\n)",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "dmesg errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "{k8s_daemonset_name=\"dmesg\"} |~ `(?i)NVRM: xid` or `(?i)error`"
      }
     ]
    }
   ]
  },
  {
   "title": "XID Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "XID Errors",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_XID_ERRORS{instance=~\"${instance}:9400\", gpu=~\"${gpu}\"}",
       "legendFormat": "GPU {{gpu}} instance {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}