apiVersion: v1
kind: Namespace
metadata:
  name: konduktor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: konduktor-controller-sa
  namespace: konduktor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: konduktor
  name: konduktor-controller-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: konduktor
  name: konduktor-controller-rolebinding
subjects:
- kind: ServiceAccount
  name: konduktor-controller-sa
  namespace: konduktor
roleRef:
  kind: ClusterRole
  name: konduktor-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konduktor-controller-deployment
  namespace: konduktor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konduktor-controller
  template:
    metadata:
      labels:
        app: konduktor-controller
    spec:
      serviceAccountName: konduktor-controller-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu
                operator: DoesNotExist
      containers:
      - name: python
        image: python:3.10
        command: ["/bin/sh"]
        args: ["-c", "pip install konduktor-nightly && python -m konduktor.controller.launch"]
        ## define what namespaces to watch for errors, comma separated.
        # env:
        #   - name: WATCHED_NAMESPACES
        #     value: "default,othernamespace"
        #   - name: LOG_ENDPOINT
        #     value: "http://loki.loki.svc.cluster.local:3100"
